# Generated by Django 4.1.2 on 2022-10-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ship_name", models.TextField()),
                ("ship_date", models.TextField()),
                ("ship_capacity", models.IntegerField()),
                ("ship_booked_seats", models.IntegerField()),
                ("ship_remained_seats", models.IntegerField()),
                ("ship_price", models.TextField()),
                ("depart_city", models.TextField()),
                ("arrive_city", models.TextField()),
                ("depart_seaport", models.TextField()),
                ("arrive_seaport", models.TextField()),
                ("depart_time", models.TextField()),
                ("arrive_time", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CheckinItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_windows", models.TextField()),
                ("boarding_port", models.TextField()),
                (
                    "ticket_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyRailApp.ticketitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookTicketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("book_status", models.TextField()),
                ("seat_id", models.TextField()),
                (
                    "ticket_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyRailApp.ticketitem",
                    ),
                ),
            ],
        ),
    ]
